# Generated by Django 5.1.6 on 2025-02-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_join', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='checkedUsers',
        ),
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
