# Generated by Django 5.1.6 on 2025-02-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_join', '0002_remove_task_checkedusers_alter_task_prio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='app_join.task'),
        ),
    ]
