# Generated by Django 5.1.6 on 2025-02-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_join', '0003_contact_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='app_join.contact'),
        ),
    ]
