# Generated by Django 5.1.6 on 2025-02-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_join', '0004_remove_contact_tasks_task_assignedto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignedTo',
        ),
        migrations.AddField(
            model_name='contact',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, related_name='assignedTo', to='app_join.task'),
        ),
    ]
