# Generated by Django 5.1.6 on 2025-02-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_join', '0006_userprofile_delete_user_alter_task_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
