# Generated by Django 5.1.6 on 2025-02-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
