# Generated by Django 4.2 on 2025-02-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_auth', '0002_remove_userprofile_email_remove_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
